### PR TITLE
Implementation of ticket (purchasing, distribution), more error handling + dates for zones. 

### PR DESCRIPTION
**Pull request by YaBoiLiangZJ**
hopefully doesnt fail github actions..... again.....

### CODE REVIEW

**Comment by YaBoiLiangZJ** [comment]
okay, managed to get github actions working. Will go through new implemented features during meeting later today.

**Comment by Thwompert** [comment]
Yep looks good!

**Comment by CoolKeed** [comment]
oki looks good

**Comment by rmmsia** [comment]
Looks okay, everything seems to be working

**Comment by VurhD-B** [comment]
Looks ok to merge. Good job!!

**Comment by markybaby** [comment]
Smells good!

**Pull request merged**
